### ISSUE TITLE
CMake throwing a LNK2019 error

### ISSUE THREAD

**Issue by ShilpaJohncy** [trailofbits/winchecksec#1041]
When trying to build the project, I keep encountering the following error:

`checksec.obj : error LNK2019: unresolved external symbol "struct peparse::_parsed_pe * __cdecl peparse::ParsePEFromFile
(char const *)" (?ParsePEFromFile@peparse@@YAPEAU_parsed_pe@1@PEBD@Z) referenced in function "public: __cdecl checksec:
:Checksec::Checksec(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (??0Check
sec@checksec@@QEAA@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) [C:\Users\<>\Desktop\Uni\Third
Year Project\winchecksec\build\winchecksec-bin.vcxproj]`

Attaching the CMake file, and a screenshot of the error.

I run the cmake command with the following flags: 
` "C:\Users\<>\Desktop\Uni\Project\Winchecksec\cmake\cmake-3.19.4-win64-x64\bin\cmake.exe" -DCMAKE_TOOLCHAIN_FILE="C:\Users\<>\Desktop\Uni\Project\vcpkg\scripts\buildsystems\vcpkg.cmake" -Dpe-parse_DIR:PATH="C:\Users\<>\Desktop\Uni\Project\vcpkg\installed\x86-windows\share\pe-parse" -Duthenticode_DIR:PATH="C:\Users\<>\Desktop\Uni\Project\vcpkg\installed\x86-windows\share\uthenticode" .. `

![cmake ](https://user-images.githubusercontent.com/54916941/107989345-06050000-6fca-11eb-8c73-8fa6d5713018.PNG)

When I run `"C:\Users\<>\Desktop\Uni\Project\Winchecksec\cmake\cmake-3.19.4-win64-x64\bin\cmake.exe" --build . --config Release` I receive a LNK2019 error

![cmake --build   --config Release](https://user-images.githubusercontent.com/54916941/107989343-056c6980-6fca-11eb-97d4-efd9392fad11.PNG)

**Comment by woodruffw** [comment]
Hmm. It looks like `uthenticode.lib` and `pe-parser-library.lib` were built for x86-32 (i.e. Win32), not x64. The default Winchecksec build is probably x64.

Could you try installing them explicitly as 64-bit?

```
vcpkg install uthenticode:x64-windows pe-parse:x64-windows
```

Once you do that, the build should work.

**Comment by woodruffw** [comment]
(Alternatively, you could pass `-A Win32` to the CMake configure step. But I see no reason to do a 32-bit build at all when you have a 64-bit host.)

**Comment by woodruffw** [comment]
For context: on Windows, `vcpkg` defaults to x86 instead of x64: https://github.com/microsoft/vcpkg/issues/1254.

**Comment by ShilpaJohncy** [comment]
Yup, that worked!!! 

Maybe adding this as a note to the READ.me file could help avoid this confusion for others in the future. But thank you so muchhh! I look forward to using this tool :)

**Comment by woodruffw** [comment]
Glad to hear it worked! Thanks again for reporting it.

> Maybe adding this as a note to the READ.me file could help avoid this confusion for others in the future. But thank you so muchhh! I look forward to using this tool :)

Yep, I'll do this.
