### ISSUE TITLE
Show CET support

### ISSUE THREAD

**Issue by yardenshafir** [trailofbits/winchecksec#1047]
Find the CET configuration of a file, added with the compilation flag /cetcompat.
This requires parsing a new debug directory entry `IMAGE_DEBUG_TYPE_EX_DLLCHARACTERISTICS` and check bit 0, indicating that the PE is compiled with /cetcompat.
The debug directory can be found through NtHeader.OptionalHeader.DataDirArray[DEBUG_DIRECTORY].VirtualAddress. Looks like at the moment pe-parser doesn't support parsing of debug directories so functionality will need to be added there first.

**Comment by woodruffw** [comment]
Possibly a dupe of #44?

**Comment by yardenshafir** [comment]
Seems like a dupe, my bad

**Comment by woodruffw** [comment]
All good, just making sure I didn't miss something 🙂 

I agree we should prioritize this!
