### ISSUE TITLE
doesn't work with 32bit PE files

### ISSUE THREAD

**Issue by sleicasper** [trailofbits/winchecksec#26]

**Comment by woodruffw** [comment]
Thanks for the report. Could you provide more information and/or a test case? Our builds work just fine with 32-bit PEs, but it's possible that some older binaries lack the structures we test for.

**Comment by sleicasper** [comment]
Hi, IMAGE_LOAD_CONFIG_DIRECTORY is different structure compiled in win32 and win
64. https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-_image_load_config_directory64

So when winchecksec is compiled in win64, it can only parse LOAD_CONFIG of 64 bit binary correctly. So my suggestion fix is that check the binary bit at first place, then use different structure to parse.

Test case: compile whatever program in 32 bit with vs2017, make sure “/GS” option is on. So the compiled binary have GS protection, but winchecksec can’t detect GS.

**Comment by GitIsNotMyFriend** [comment]
Can I work on this?

**Comment by woodruffw** [comment]
Yes, please do!

**Comment by GitIsNotMyFriend** [comment]
It seems like ImageHlp isn't really capable of distinguishing between 32bit processes and 64bit processes which makes the parsing task much more difficult and unfortunately I don't have enough time to work on that task.

**Comment by woodruffw** [comment]
> It seems like ImageHlp isn't really capable of distinguishing between 32bit processes and 64bit processes which makes the parsing task much more difficult and unfortunately I don't have enough time to work on that task.

Yeah, I think we've reached the end of the road in terms of using `ImageHlp`. I've opened #27 to track replacing it with pe-parse, work on that would definitely be appreciated.
