### ISSUE TITLE
Explain the output

### ISSUE THREAD

**Issue by rowlap** [trailofbits/winchecksec#30]
As a wishlist item, I'd like to better understand the output of winchecksec.

Please provide a newbie page under
https://github.com/trailofbits/winchecksec/wiki
explaining what each of the fields means, a short description of each, and links to the reference documentation.

As an end-user, I'm just curious, but as a developer, I might want some expert guidance on which security features are worth the effort to enable.

**Comment by woodruffw** [comment]
Thanks for the feedback @rowlap! I've marked this for community help; I'll also make sure the Wiki is externally editable by non-maintainers.

**Comment by rowlap** [comment]
I've boldly gone ahead and added
https://github.com/trailofbits/winchecksec/wiki/winchecksec-output,-explained

Suggest leaving this ticket open for the "help wanted" aspect until there's _something_ in each section. I'll try to fill in the ones I know about.

**Comment by woodruffw** [comment]
Update: The JSON output (enabled with `-j` now contains) a `description` field for each mitigation. We'd be happy to accept PRs that add more fields, e.g. links to the MSDN documentation for each mitigation.
