### ISSUE TITLE
Test Framework

### ISSUE THREAD

**Issue by haxmeadroom** [trailofbits/winchecksec#47]
Add some basic pre-commit testing that runs winchecksec on a few exe's and checks the results.

**Comment by woodruffw** [comment]
By pre-commit do you mean a commit hook, or in the CI? I'd prefer it if we add this to the CI so that external contributors don't need to share or configure our commit hook setup, but not sure if that's what you meant anyways 🙂

**Comment by haxmeadroom** [comment]
Maybe pre-commit isn't the right word. I like to `make test` and have say pytest run some regression tests before committing.

**Comment by woodruffw** [comment]
Gotcha. That SGTM, as long as we can also enable it in the CI!

**Comment by haxmeadroom** [comment]
Is there a collection anywhere of PE's that have various flags set we could throw into a `test/` directory and run against? We could compile a helloworld.c with different flags I suppose.

**Comment by haxmeadroom** [comment]
I've never done CI so I have no idea how it works. A there certain things to do / not do that make it easier to integrate with CI?

**Comment by woodruffw** [comment]
> Is there a collection anywhere of PE's that have various flags set we could throw into a `test/` directory and run against? We could compile a helloworld.c with different flags I suppose.

We could probably fetch some of the [SysInternals](https://docs.microsoft.com/en-us/sysinternals/) EXEs and use them for tests, although I'm not sure about licensing. A `helloworld.c` that we build a few different times with different flags sounds good to me, though.



> I've never done CI so I have no idea how it works. Are there certain things to do / not do that make it easier to integrate with CI?

Nothing in particular; if the tests can be run with `make test` and exit with a non-zero code on failure, that would be perfect 🙂

**Comment by woodruffw** [comment]
I created [pegoat](https://github.com/trailofbits/pegoat) to supply PEs for our testing needs. We can either submodule it here or do some kind of artifact management with GitHub Actions to get its build products for testing.

**Comment by ekilmer** [comment]
> either submodule it here or do some kind of artifact management with GitHub Actions to get its build products for testing.

Submodule would enable people who clone the repo to easily build, contribute, and run tests locally.

GitHub Actions would (hopefully) enable more elegant build artifact caching to skip building the examples every time.

Doing both would mean updating commit SHAs in two places, which is a bit annoying.


Hmmmm. If we had an initial stage, similar to linting, that had build caching turned on, we'd be able to build the examples in the submodule quickly, and it would only be a single place to update the git SHA. Not sure how to deal with `CMakeLists.txt` files, but if we had a fast way to do something like `make test-binaries` which is run before each platform's build, then that would be nice.
