### ISSUE TITLE
Support ELF

### ISSUE THREAD

**Issue by haxmeadroom** [trailofbits/winchecksec#48]
Would be cool to also support ELF like the original checksec.
http://www.trapkit.de/tools/checksec.html

**Comment by woodruffw** [comment]
I definitely agree that it'd be good to have a maintained checksec replacement in our toolbelt, but I don't know if it's a good fit for winchecksec itself -- I'd personally like to see winchecksec do one thing (statically analyzing PEs) as "right" as possible, and then embed it in a larger toolset/framework for handling multiple executable formats. Thoughts?

**Comment by haxmeadroom** [comment]
I'll need to investigate how much is involved to support features similar to checksec for elf.
