### ISSUE TITLE
Don't report SAFESEH for x64 binaries

### ISSUE THREAD

**Issue by disconnect3d** [trailofbits/winchecksec#64]
According to https://docs.microsoft.com/en-us/cpp/build/reference/safeseh-image-has-safe-exception-handlers?view=vs-2019:
> /SAFESEH is only valid when linking for x86 targets. /SAFESEH is not supported for platforms that already have the exception handlers noted. For example, on x64 and ARM, all exception handlers are noted in the PDATA. ML64.exe has support for adding annotations that emit SEH information (XDATA and PDATA) into the image, allowing you to unwind through ml64 functions. See MASM for x64 (ml64.exe) for more information.

The SAFESEH only applies for x86 (32-bit)/PE binaries.

I am not sure if we report it for x64/PE+ binaries but if we do, we should not do that or mark it as it doesn't apply to x64 binaries.

Additionally, we should make sure the README points this out too, so we should change:
> Structured Exception Handling and SafeSEH support

Into:
> Structured Exception Handling and SafeSEH support (for x86 binaries, where it applies)

**Comment by woodruffw** [comment]
Ah, read my mind. I opened #67 for this as well, will close mine and copy my refactor idea.
