### ISSUE TITLE
Revisit output format for mitigation presence

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/winchecksec#66]
We currently model the presence of mitigations as `true` or `false`, making a partially arbitrary choice when a mitigation doesn't apply (e.g. ASLR on .NET, SafeSEH on x86_64). Instead, we should model presence as `true`, `false`, or `"N/A"`.

**Comment by woodruffw** [comment]
More generally, we should remodel the output away from:

```
{
  "mitigation": bool
}
```

to: 

```
{
  "mitigation": {
    "present": bool | "N/A",
    "flag": "/WHATEVER",
    "description": "whatever"
  }
]
```

**Comment by haxmeadroom** [comment]
Yeah, I was also wanting more granularity than true or false. Might need unimplemented or other conditions besides N/A (for WinVerifyTrust for example).

**Comment by haxmeadroom** [comment]
Maybe each flag should have true/false/other, and a text field to describe the details?

**Comment by woodruffw** [comment]
> Maybe each flag should have true/false/other, and a text field to describe the details?

That sounds good to me!

**Comment by haxmeadroom** [comment]
We could also put a @disconnect3d 's `--info` there, or maybe that makes sense for another completely new field.

**Comment by woodruffw** [comment]
New field makes sense to me -- I was thinking `description` or similar.

**Comment by woodruffw** [comment]
I'm going to take a stab at this now, since I'm waiting on builds 😅
