### ISSUE TITLE
winchecksec tool crashes while scanning DLLs built from latest version of Visual Studio

### ISSUE THREAD

**Issue by shreyas-m791** [trailofbits/winchecksec#78]
**Platform**: Windows 10 16229.192
**Visual Studio**: Professional 2019 16.6.2
**Command**: winchecksec.exe example.dll

**Comment by woodruffw** [comment]
Thanks for the report. Could you provide a copy of your `example.dll`?

**Comment by shreyas-m791** [comment]
> Thanks for the report. Could you provide a copy of your `example.dll`?

I cannot provide the actual DLL due to my company's policies. So I have attached the winchecksec.dll here which was also built with the same version of Visual Studio. Hope this helps.
[winchecksec.zip](https://github.com/trailofbits/winchecksec/files/4823512/winchecksec.zip)

**Comment by woodruffw** [comment]
Thanks, I'll try to repro with the sample you've sent.

**Comment by woodruffw** [comment]
I was unable to repro on macOS. Trying on Windows now.

**Comment by woodruffw** [comment]
I was unable to repro this on Windows with the latest `master`. `foo.dll` here is the `winchecksec.dll` you sent me:

<img width="510" alt="Screen Shot 2020-06-24 at 11 00 19 AM" src="https://user-images.githubusercontent.com/3059210/85580641-e7e92a80-b609-11ea-8920-f87496ca58c9.png">

**Comment by shreyas-m791** [comment]
> I was unable to repro this on Windows with the latest `master`. `foo.dll` here is the `winchecksec.dll` you sent me:
> 
> <img alt="Screen Shot 2020-06-24 at 11 00 19 AM" width="510" src="https://user-images.githubusercontent.com/3059210/85580641-e7e92a80-b609-11ea-8920-f87496ca58c9.png">
> 
> Do you have any additional information about your build system, build flags, etc?

My bad. The winchecksec tool integrated with our project is an older version (1.1.1). Since there is no crash with the latest version of winchecksec I am closing this issue. Thanks for your time.

**Comment by woodruffw** [comment]
No sweat! Thanks for clearing it up.
