### ISSUE TITLE
How to compile on Linux

### ISSUE THREAD

**Issue by electricworry** [trailofbits/winchecksec#80]
I'm confused about how to build this on linux. Don't know how best to fulfil the pe-parse requirement. Running "cmake --build . --target install" for that dependency does not seem to install anything.

Can anyone please help?

**Comment by woodruffw** [comment]
The easiest way to install `pe-parse` (and `uthenticode`, which is also required) on Linux is to use `vcpkg`, as indicated in the README. You're welcome to try installing the dependencies manually, but this isn't an actively supported development pattern.

**Comment by bonafideduck** [comment]
I used the following script to build this on Ubuntu 20.04 when I needed it for my job(1).  It may not be the proper way to install and use vcpkg, but it least worked for me.

```bash
#!/bin/bash

mkdir -p /contrib
apt-get update
apt-get install -y git curl unzip tar gcc g++ cmake

cd /contrib
git config --global advice.detachedHead false
git clone -b 2020.07 https://github.com/Microsoft/vcpkg
git clone https://github.com/trailofbits/winchecksec.git
mkdir /contrib/winchecksec/build

cd /contrib/vcpkg
export VCPKG_DISABLE_METRICS=1
./bootstrap-vcpkg.sh
/contrib/vcpkg/vcpkg install pe-parse
/contrib/vcpkg/vcpkg install uthenticode

cd /contrib/winchecksec/build
cmake -DCMAKE_TOOLCHAIN_FILE=/contrib/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release ..
cmake --build .
cmake --install .
ln -s /contrib/winchecksec/build/winchecksec /bin/winchecksec
```

---
(1) I am Mark Eklund, an employee of Zoom Video Communications.

**Comment by woodruffw** [comment]
Thanks for the writeup! That looks pretty close to a reasonable `vcpkg` usage pattern to me 🙂
