### ISSUE TITLE
Out of bounds copy from loadConfigData to loadConfig.

### ISSUE THREAD

**Issue by bonafideduck** [trailofbits/winchecksec#84]
[The below code](https://github.com/trailofbits/winchecksec/blob/535606ef4f0990fda5c9d13b1d58242d01e60759/checksec.cpp#L88) checks to see if the `loadConfiData.size()` is greater than `loadConfig `but does not check to see if it is as big as `loadConfig`.  It then does a `memcpy` of `loadConfiData.data()` to `loadConfig` of size `sizeof(loadConfig)`.  In my tests, `loadConfigData.size()` is 64 and  is `sizeof(loadConfig)` is 164.  So 100 random bytes are being copied into loadConfig.  The RFG test gives inconsistent results because it references these random bytes.

```cpp
        peparse::image_load_config_64 loadConfig;
        if (loadConfigData.size() > sizeof(loadConfig)) {
            std::cerr << "Warn: large load config, probably contains undocumented "
                         "fields"
                      << "\n";
        }
        memcpy(&loadConfig, loadConfigData.data(), sizeof(loadConfig));
```

**Comment by woodruffw** [comment]
Thanks for the catch. Yeah, we should both brace-initialize `loadConfig` to make sure that it's zeroed and also add a warning on a short config.
