### ISSUE TITLE
Unable to build on Ubuntu

### ISSUE THREAD

**Issue by naren-jayram** [trailofbits/winchecksec#86]
**System Details:**

Virtualization: vmware
Operating System: Ubuntu 18.04.4 LTS
Kernel: Linux 4.15.0-88-generic
Architecture: x86-64
cmake version 3.19.0

![image](https://user-images.githubusercontent.com/25578608/100112275-0f803f80-2e95-11eb-9093-1fa270a963d0.png)

**How am I building?**
$ git clone https://github.com/trailofbits/winchecksec.git
$ cd winchecksec
$ mkdir build
$ cd build
$ export CMAKE_PREFIX_PATH=/home/iot/tools/vcpkg/packages/pe-parse_x64-linux/share/pe-parse/
$ export CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH:/home/iot/tools/vcpkg/packages/uthenticode_x64-linux/share/uthenticode

root@xyz ~/t/w/build# cmake -DCMAKE_BUILD_TYPE=Release ..
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/iot/tools/winchecksec/build

root@xyz ~/t/w/build# cmake --build .
Scanning dependencies of target winchecksec
[ 20%] Building CXX object CMakeFiles/winchecksec.dir/checksec.cpp.o
[ 40%] Linking CXX static library libwinchecksec.a
[ 40%] Built target winchecksec
Scanning dependencies of target winchecksec-bin
[ 60%] Building CXX object CMakeFiles/winchecksec-bin.dir/checksec.cpp.o
[ 80%] Building CXX object CMakeFiles/winchecksec-bin.dir/main.cpp.o
make[2]: *** No rule to make target '/home/iot/tools/vcpkg/packages/uthenticode_x64-linux/lib/libcrypto.a', needed by 'winchecksec'.  Stop.
CMakeFiles/Makefile2:123: recipe for target 'CMakeFiles/winchecksec-bin.dir/all' failed
make[1]: *** [CMakeFiles/winchecksec-bin.dir/all] Error 2
Makefile:102: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by woodruffw** [comment]
Thanks for the report. It looks like you're using `CMAKE_PREFIX_PATH` to pass the dependencies to the winchecksec build, which will miss transitive deps like `openssl`. You should use `CMAKE_TOOLCHAIN_FILE` instead:

```bash
cmake -DCMAKE_TOOLCHAIN_FILE=[path to vcpkg]/scripts/buildsystems/vcpkg.cmake ..
```

That should fix the issue with `libcrypto.a`, but I'll keep this issue open in case it doesn't.

**Comment by naren-jayram** [comment]
Thank you very much. It solved the issue.

**Comment by woodruffw** [comment]
No problem. Let us know if you have any others.
